import { createClient } from '@supabase/supabase-js';
import config from 'dotenv';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');
config.config({ path: join(rootDir, '.env.local') });
config.config({ path: join(rootDir, '.env') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!supabaseUrl || !serviceRoleKey) {
  console.error("❌ Missing Supabase URL or Service Role Key");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, serviceRoleKey);

const INSPECTOR = {
  id: '07768f16-9295-43a2-b989-8ab518bb9b8a',
  name: 'Peter Parker',
  email: 'inspection@gmail.com',
  phone: '0321454789879',
};

const UK_25_CARS = [
  // 1. BMW 3 Series
  {
    title: '2023 BMW 3 Series 330e M Sport Pro Saloon 2.0 4dr',
    brand: 'BMW',
    model: '3 Series',
    year: 2023,
    price: 31990,
    currency: 'GBP',
    mileage: 14200,
    transmission: 'Automatic',
    fuel_type: 'Hybrid',
    body_type: 'Sedan',
    exterior_color: 'Portimao Blue Metallic',
    interior_color: 'Vernasca Black Leather',
    color: 'Portimao Blue',
    engine: '2.0L Turbo Hybrid',
    engine_capacity: '1998 cc',
    horsepower: 292,
    condition: 'Certified Used',
    city: 'London',
    location: 'Mayfair, London, UK',
    description: 'Immaculate 2023 BMW 330e M Sport Pro in Portimao Blue with M Sport Pro Pack, Harman Kardon Surround Sound, HUD, and Technology Pack. Verified main dealer service history.',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',
    features: ['M Sport Pro Pack', 'Harman Kardon Audio', 'Head-Up Display', 'Live Cockpit Professional', 'Adaptive M Suspension', 'Parking Assistant Plus'],
    badge: 'Verified Inspection',
    rating: 4.9,
    status: 'approved',
    is_featured: true,
    views_count: 142,
    seller_name: 'Mayfair Prestige Motors',
    seller_phone: '+44 20 7946 0912',
    seller_email: 'sales@mayfairprestige.co.uk',
    is_inspected: true,
    inspection_rating: 9.8,
    inspection_notes: 'Passed 215-point inspection with top scores. Battery health 99%, zero bodywork defects.',
    inspected_at: new Date('2026-07-20T10:00:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 2. Audi A4 Avant
  {
    title: '2022 Audi A4 Avant 40 TFSI S Line S Tronic 5dr',
    brand: 'Audi',
    model: 'A4 Avant',
    year: 2022,
    price: 26450,
    currency: 'GBP',
    mileage: 22800,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    body_type: 'Estate',
    exterior_color: 'Daytona Grey Pearl',
    interior_color: 'Fine Nappa Leather S Black',
    color: 'Daytona Grey',
    engine: '2.0L TFSI Mild Hybrid',
    engine_capacity: '1984 cc',
    horsepower: 204,
    condition: 'Excellent',
    city: 'Manchester',
    location: 'Deansgate, Manchester, UK',
    description: 'Stunning Audi A4 Avant S Line in Daytona Grey. Features Virtual Cockpit Plus, MMI Touchscreen, Matrix LED Headlights, and 19" 5-arm rotor alloys.',
    images: [
      'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80',
    features: ['Audi Virtual Cockpit Plus', 'Matrix LED Headlights', 'MMI Navigation Plus', 'Power Tailgate', '3-Zone Climate Control'],
    badge: 'Inspector Certified',
    rating: 4.8,
    status: 'approved',
    is_featured: true,
    views_count: 118,
    seller_name: 'Manchester Executive Cars',
    seller_phone: '+44 161 496 0221',
    seller_email: 'sales@manchestercars.co.uk',
    is_inspected: true,
    inspection_rating: 9.6,
    inspection_notes: 'Fully verified by Peter Parker. Engine, S Tronic gearbox and chassis in top order.',
    inspected_at: new Date('2026-07-19T14:30:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 3. Mercedes-Benz A-Class
  {
    title: '2022 Mercedes-Benz A-Class A200 AMG Line Executive 1.3 5dr',
    brand: 'Mercedes-Benz',
    model: 'A-Class',
    year: 2022,
    price: 22890,
    currency: 'GBP',
    mileage: 18500,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    body_type: 'Hatchback',
    exterior_color: 'Digital White Metallic',
    interior_color: 'Artico Leather / Dinamica Black',
    color: 'Digital White',
    engine: '1.3L Turbocharged',
    engine_capacity: '1332 cc',
    horsepower: 163,
    condition: 'Certified Used',
    city: 'Birmingham',
    location: 'Edgbaston, Birmingham, UK',
    description: 'Top-spec Mercedes A200 AMG Line Executive with MBUX Widescreen Displays, Heated Leather Seats, Active Parktronic, and 18" AMG wheels.',
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
    features: ['MBUX Dual Widescreen', 'AMG Body Styling', 'Heated Seats', '64-Color Ambient Lighting', 'Reversing Camera'],
    badge: 'Verified Inspection',
    rating: 4.8,
    status: 'approved',
    is_featured: true,
    views_count: 95,
    seller_name: 'Midlands Star Approved Cars',
    seller_phone: '+44 121 496 0883',
    seller_email: 'info@midlandsstar.co.uk',
    is_inspected: true,
    inspection_rating: 9.5,
    inspection_notes: 'All diagnostics clear, zero fault codes, pristine exterior paint depth.',
    inspected_at: new Date('2026-07-21T11:15:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 4. Land Rover Range Rover Sport
  {
    title: '2023 Land Rover Range Rover Sport 3.0 D300 Dynamic SE 5dr Auto',
    brand: 'Land Rover',
    model: 'Range Rover Sport',
    year: 2023,
    price: 74990,
    currency: 'GBP',
    mileage: 9800,
    transmission: 'Automatic',
    fuel_type: 'Diesel',
    body_type: 'SUV',
    exterior_color: 'Carpathian Grey Premium Metallic',
    interior_color: 'Ebony Perforated Windsor Leather',
    color: 'Carpathian Grey',
    engine: '3.0L Straight-6 Twin Turbo Diesel',
    engine_capacity: '2996 cc',
    horsepower: 300,
    condition: 'Like New',
    city: 'Oxford',
    location: 'Summertown, Oxford, UK',
    description: 'Ultra-luxury Range Rover Sport D300 Dynamic SE. Equipped with Meridian Sound, 13.1" Pivi Pro Touchscreen, Panoramic Sunroof, and 22" Satin Dark Grey alloys.',
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1519245659620-e859806a8d3b?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80',
    features: ['Meridian 3D Surround Sound', 'Sliding Panoramic Roof', 'Air Suspension', 'Pixel LED Headlights', 'Soft Door Close'],
    badge: 'Premium Certified',
    rating: 5.0,
    status: 'approved',
    is_featured: true,
    views_count: 230,
    seller_name: 'Oxfordshire Specialist Automobiles',
    seller_phone: '+44 1865 496 0332',
    seller_email: 'vip@oxfordautos.co.uk',
    is_inspected: true,
    inspection_rating: 9.9,
    inspection_notes: 'Pristine 200-point report. Drivetrain, air suspension, and electronics flawless.',
    inspected_at: new Date('2026-07-22T09:00:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 5. Porsche 911 Carrera S
  {
    title: '2021 Porsche 911 3.0T 992 Carrera S PDK 2dr',
    brand: 'Porsche',
    model: '911 Carrera S',
    year: 2021,
    price: 89950,
    currency: 'GBP',
    mileage: 12400,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    body_type: 'Coupe',
    exterior_color: 'Crayon Grey',
    interior_color: 'Black Leather Package',
    color: 'Crayon Grey',
    engine: '3.0L Twin-Turbo Flat-6',
    engine_capacity: '2981 cc',
    horsepower: 450,
    condition: 'Pristine',
    city: 'Cambridge',
    location: 'City Centre, Cambridge, UK',
    description: 'Iconic 992 Porsche 911 Carrera S in Crayon Grey with Sport Chrono Pack, Sports Exhaust, BOSE Sound, PASM (-10mm), and 20/21" RS Spyder alloys.',
    images: [
      'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80',
    features: ['Sport Chrono Package', 'Sports Exhaust System', 'BOSE Surround Sound', 'PASM Sport Suspension', 'LED Matrix Lights'],
    badge: 'Supercar Verified',
    rating: 5.0,
    status: 'approved',
    is_featured: true,
    views_count: 310,
    seller_name: 'Cambridge Performance Cars',
    seller_phone: '+44 1223 496 0774',
    seller_email: 'sales@cambridgeperformance.co.uk',
    is_inspected: true,
    inspection_rating: 9.9,
    inspection_notes: 'Porsche Approved inspection verified. DME report clean with zero over-revs.',
    inspected_at: new Date('2026-07-18T16:00:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 6. Volkswagen Golf R
  {
    title: '2023 Volkswagen Golf R 2.0 TSI 4Motion 320 PS DSG 5dr',
    brand: 'Volkswagen',
    model: 'Golf R',
    year: 2023,
    price: 34950,
    currency: 'GBP',
    mileage: 11200,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    body_type: 'Hatchback',
    exterior_color: 'Lapiz Blue Metallic',
    interior_color: 'Nappa Leather R Seats',
    color: 'Lapiz Blue',
    engine: '2.0L TSI Turbo 4Motion',
    engine_capacity: '1984 cc',
    horsepower: 320,
    condition: 'Excellent',
    city: 'Leeds',
    location: 'Headingley, Leeds, UK',
    description: 'Mk8 VW Golf R finished in Lapiz Blue. Equipped with R Performance Pack (Drift Mode), Akrapovic Titanium Exhaust, Panoramic Roof, DCC, and 19" Estoril wheels.',
    images: [
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80',
    features: ['R Performance Pack & Drift Mode', 'Akrapovic Exhaust', 'Dynamic Chassis Control', 'IQ.LIGHT Matrix LEDs', 'Nappa Leather Seats'],
    badge: 'Hot Hatch Certified',
    rating: 4.9,
    status: 'approved',
    is_featured: true,
    views_count: 175,
    seller_name: 'Yorkshire Performance Vehicles',
    seller_phone: '+44 113 496 0551',
    seller_email: 'sales@ypv.co.uk',
    is_inspected: true,
    inspection_rating: 9.7,
    inspection_notes: 'Inspected by Peter Parker. Differential, launch system, and mechanicals 100% verified.',
    inspected_at: new Date('2026-07-20T15:20:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 7. Tesla Model 3
  {
    title: '2022 Tesla Model 3 Long Range Dual Motor AWD 4dr Auto',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2022,
    price: 27990,
    currency: 'GBP',
    mileage: 21000,
    transmission: 'Automatic',
    fuel_type: 'Electric',
    body_type: 'Sedan',
    exterior_color: 'Pearl White Multi-Coat',
    interior_color: 'Premium All Black',
    color: 'Pearl White',
    engine: 'Dual Electric Motor AWD',
    engine_capacity: '75 kWh',
    horsepower: 434,
    condition: 'Certified EV',
    city: 'Edinburgh',
    location: 'West End, Edinburgh, UK',
    description: 'Refresh 2022 Tesla Model 3 Long Range AWD with Heat Pump, Power Trunk, AMD Ryzen Processor, 14-Speaker Premium Audio, and Heated Seats.',
    images: [
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1536700503339-1e4b06520771?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80',
    features: ['Dual Motor AWD', 'AMD Ryzen Computer', 'Heat Pump', '14-Speaker Premium Sound', 'Autopilot'],
    badge: 'EV Certified',
    rating: 4.8,
    status: 'approved',
    is_featured: false,
    views_count: 140,
    seller_name: 'Scottish EV Hub',
    seller_phone: '+44 131 496 0992',
    seller_email: 'info@scottishev.co.uk',
    is_inspected: true,
    inspection_rating: 9.6,
    inspection_notes: 'Battery SOH test passed at 98.4%. Drive motors and thermal management fully healthy.',
    inspected_at: new Date('2026-07-21T13:45:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 8. MINI Cooper S
  {
    title: '2022 MINI Hatch 2.0 Cooper S Exclusive Auto 3dr',
    brand: 'MINI',
    model: 'Cooper S',
    year: 2022,
    price: 19850,
    currency: 'GBP',
    mileage: 15600,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    body_type: 'Hatchback',
    exterior_color: 'British Racing Green IV',
    interior_color: 'MINI Yours Satellite Grey Leather',
    color: 'British Racing Green',
    engine: '2.0L TwinPower Turbo',
    engine_capacity: '1998 cc',
    horsepower: 178,
    condition: 'Excellent',
    city: 'Bristol',
    location: 'Clifton, Bristol, UK',
    description: 'Charming British Racing Green MINI Cooper S Exclusive with Panoramic Glass Roof, Digital Cockpit, Comfort Plus Pack, and Harman Kardon Sound.',
    images: [
      'https://images.unsplash.com/photo-1617654112365-307921291f42?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1617654112365-307921291f42?auto=format&fit=crop&w=1200&q=80',
    features: ['MINI Yours Leather', 'Panoramic Sunroof', 'Digital Cockpit', 'Harman Kardon Audio', 'Union Jack Rear Lights'],
    badge: 'Verified Inspection',
    rating: 4.7,
    status: 'approved',
    is_featured: false,
    views_count: 88,
    seller_name: 'West Country Motor Group',
    seller_phone: '+44 117 496 0441',
    seller_email: 'sales@westcountrymotors.co.uk',
    is_inspected: true,
    inspection_rating: 9.4,
    inspection_notes: 'Full service history checked. Mint interior and flawless mechanical operation.',
    inspected_at: new Date('2026-07-19T09:30:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 9. Ford Focus ST
  {
    title: '2022 Ford Focus ST 2.3 EcoBoost 280 PS 5dr',
    brand: 'Ford',
    model: 'Focus ST',
    year: 2022,
    price: 24200,
    currency: 'GBP',
    mileage: 19400,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    body_type: 'Hatchback',
    exterior_color: 'Mean Green',
    interior_color: 'Ford Performance Sports Seats',
    color: 'Mean Green',
    engine: '2.3L EcoBoost Turbo',
    engine_capacity: '2261 cc',
    horsepower: 280,
    condition: 'Great',
    city: 'Liverpool',
    location: 'Waterfront, Liverpool, UK',
    description: 'Ford Focus ST in Mean Green with Performance Pack (eLSD, Track Mode, Launch Control), B&O 10-speaker audio, and 13.2" SYNC 4 touchscreen.',
    images: [
      'https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=1200&q=80',
    features: ['Performance Pack & Track Mode', 'eLSD Limited Slip Diff', 'B&O Audio System', '13.2" SYNC 4 Touchscreen'],
    badge: 'Inspector Certified',
    rating: 4.8,
    status: 'approved',
    is_featured: false,
    views_count: 105,
    seller_name: 'Merseyside Hot Hatches',
    seller_phone: '+44 151 496 0339',
    seller_email: 'sales@merseysidehothatches.co.uk',
    is_inspected: true,
    inspection_rating: 9.5,
    inspection_notes: 'eLSD differential test passed. Smooth manual gearshift, pristine turbo pressure.',
    inspected_at: new Date('2026-07-20T17:10:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 10. Land Rover Defender 110
  {
    title: '2023 Land Rover Defender 110 3.0 D250 SE 5dr Auto',
    brand: 'Land Rover',
    model: 'Defender 110',
    year: 2023,
    price: 62450,
    currency: 'GBP',
    mileage: 13500,
    transmission: 'Automatic',
    fuel_type: 'Diesel',
    body_type: 'SUV',
    exterior_color: 'Pangea Green / White Roof',
    interior_color: 'Acorn Grained Leather',
    color: 'Pangea Green',
    engine: '3.0L Straight-6 Diesel MHEV',
    engine_capacity: '2996 cc',
    horsepower: 249,
    condition: 'Excellent',
    city: 'Newcastle',
    location: 'Quayside, Newcastle, UK',
    description: 'Iconic Defender 110 SE in Pangea Green with White contrast roof, Air Suspension, ClearSight Mirror, Meridian Sound, and 3D Surround Camera.',
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    features: ['Air Suspension', 'ClearSight Rear View Mirror', 'Terrain Response 2', '3D Surround Camera', 'Tow Package'],
    badge: 'Verified Inspection',
    rating: 4.9,
    status: 'approved',
    is_featured: true,
    views_count: 198,
    seller_name: 'Northumbria 4x4 Centre',
    seller_phone: '+44 191 496 0772',
    seller_email: 'sales@northumbria4x4.co.uk',
    is_inspected: true,
    inspection_rating: 9.8,
    inspection_notes: 'Underbody clean, no rust or offroad scraping. Air suspension holds pressure 100%.',
    inspected_at: new Date('2026-07-21T16:00:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 11. Jaguar F-Pace
  {
    title: '2023 Jaguar F-Pace 2.0 P400e R-Dynamic HSE Black 5dr Auto',
    brand: 'Jaguar',
    model: 'F-Pace',
    year: 2023,
    price: 48990,
    currency: 'GBP',
    mileage: 10800,
    transmission: 'Automatic',
    fuel_type: 'Hybrid',
    body_type: 'SUV',
    exterior_color: 'Santorini Black Metallic',
    interior_color: 'Ebony Windsor Leather',
    color: 'Santorini Black',
    engine: '2.0L Turbo Plug-in Hybrid',
    engine_capacity: '1997 cc',
    horsepower: 404,
    condition: 'Certified Used',
    city: 'London',
    location: 'Kensington, London, UK',
    description: '404hp Jaguar F-Pace P400e R-Dynamic HSE Black. Features Black Exterior Pack, Panoramic Sunroof, Meridian 3D Sound, and 21" Gloss Black alloys.',
    images: [
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1541348263662-e082662d82da?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80',
    features: ['404PS Plug-in Hybrid', 'Black Pack', 'Meridian 3D Sound', 'Panoramic Sunroof', '16-Way Heated Seats'],
    badge: 'Verified Inspection',
    rating: 4.8,
    status: 'approved',
    is_featured: false,
    views_count: 112,
    seller_name: 'Kensington Luxury Motors',
    seller_phone: '+44 20 7946 0884',
    seller_email: 'sales@kensingtonmotors.co.uk',
    is_inspected: true,
    inspection_rating: 9.7,
    inspection_notes: 'PHEV range verified at 32 miles EV mode. Paint inspection completely flawless.',
    inspected_at: new Date('2026-07-22T11:20:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 12. Volvo XC90
  {
    title: '2023 Volvo XC90 2.0 T8 Recharge Ultimate Dark 5dr Auto 7 Seat',
    brand: 'Volvo',
    model: 'XC90',
    year: 2023,
    price: 56990,
    currency: 'GBP',
    mileage: 16200,
    transmission: 'Automatic',
    fuel_type: 'Hybrid',
    body_type: 'SUV',
    exterior_color: 'Onyx Black Metallic',
    interior_color: 'Nappa Leather Charcoal',
    color: 'Onyx Black',
    engine: '2.0L Turbo & Supercharged Hybrid',
    engine_capacity: '1969 cc',
    horsepower: 455,
    condition: 'Pristine',
    city: 'Sheffield',
    location: 'Ecclesall, Sheffield, UK',
    description: 'Flagship 7-Seater 455hp Volvo XC90 T8 Recharge Ultimate Dark. Bowers & Wilkins Hi-Fi Audio, Air Suspension, Panoramic Sunroof, HUD, and Massage Seats.',
    images: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    features: ['Bowers & Wilkins Audio', 'Air Suspension', '7 Seats', 'Massage Seats', 'Pilot Assist'],
    badge: 'Luxury Family SUV',
    rating: 4.9,
    status: 'approved',
    is_featured: true,
    views_count: 156,
    seller_name: 'Peak District Executive Cars',
    seller_phone: '+44 114 496 0229',
    seller_email: 'sales@peakdistrictcars.co.uk',
    is_inspected: true,
    inspection_rating: 9.8,
    inspection_notes: 'Verified by Peter Parker. All 7 seat mechanisms and hybrid power systems immaculate.',
    inspected_at: new Date('2026-07-21T15:00:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 13. Bentley Continental GT
  {
    title: '2022 Bentley Continental GT 4.0 V8 Mulliner Driving Spec 2dr Auto',
    brand: 'Bentley',
    model: 'Continental GT',
    year: 2022,
    price: 145000,
    currency: 'GBP',
    mileage: 8200,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    body_type: 'Coupe',
    exterior_color: 'Glacier White',
    interior_color: 'Beluga Hide with Diamond Quilting',
    color: 'Glacier White',
    engine: '4.0L Twin-Turbo V8',
    engine_capacity: '3996 cc',
    horsepower: 550,
    condition: 'Pristine',
    city: 'Mayfair',
    location: 'Berkeley Square, London, UK',
    description: 'Exquisite Bentley Continental GT V8 Mulliner Specification. Features Naim for Bentley 2200W Sound System, Rotating Display, Touring Spec, and 22" Black Painted Alloys.',
    images: [
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
    features: ['Mulliner Driving Specification', 'Naim 2200W Audio', 'Bentley Rotating Display', 'Touring Spec', 'Night Vision'],
    badge: 'Ultra Luxury',
    rating: 5.0,
    status: 'approved',
    is_featured: true,
    views_count: 420,
    seller_name: 'Jack Barclay Bentley',
    seller_phone: '+44 20 7499 3850',
    seller_email: 'sales@bentleymayfair.co.uk',
    is_inspected: true,
    inspection_rating: 9.9,
    inspection_notes: 'Bentley Certified Inspection passed. Air suspension, twin turbo V8, and handcrafted leather immaculate.',
    inspected_at: new Date('2026-07-22T14:00:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 14. Aston Martin DB11
  {
    title: '2021 Aston Martin DB11 4.0 V8 Coupe 2dr Auto',
    brand: 'Aston Martin',
    model: 'DB11',
    year: 2021,
    price: 112500,
    currency: 'GBP',
    mileage: 11400,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    body_type: 'Coupe',
    exterior_color: 'Magnetic Silver Metallic',
    interior_color: 'Obsidian Black Leather with Spicy Red Stitching',
    color: 'Magnetic Silver',
    engine: '4.0L Twin-Turbo V8',
    engine_capacity: '3982 cc',
    horsepower: 510,
    condition: 'Pristine',
    city: 'Southampton',
    location: 'Marina, Southampton, UK',
    description: 'Iconic Aston Martin DB11 V8 Coupe in Magnetic Silver. Features Bang & Olufsen BeoSound Audio, Celestial Perforated Seats, Nexus Quilting, and 20" 10-spoke Directional Alloys.',
    images: [
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80',
    features: ['Bang & Olufsen BeoSound', 'Celestial Perforated Leather', 'Technology Pack', '360 Camera', 'Sports Exhaust'],
    badge: 'Exotic Verified',
    rating: 5.0,
    status: 'approved',
    is_featured: true,
    views_count: 285,
    seller_name: 'Solent Aston Martin Specialists',
    seller_phone: '+44 23 8094 0112',
    seller_email: 'sales@solentaston.co.uk',
    is_inspected: true,
    inspection_rating: 9.8,
    inspection_notes: 'Certified 140-point inspection completed by Peter Parker. Twin-turbo V8 engine diagnostic clean.',
    inspected_at: new Date('2026-07-20T12:00:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 15. Nissan Qashqai
  {
    title: '2023 Nissan Qashqai 1.3 DIG-T MH N-Connecta 5dr',
    brand: 'Nissan',
    model: 'Qashqai',
    year: 2023,
    price: 21490,
    currency: 'GBP',
    mileage: 14500,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    body_type: 'SUV',
    exterior_color: 'Ceramic Grey with Black Roof',
    interior_color: 'Cloth Anthracite',
    color: 'Ceramic Grey',
    engine: '1.3L DIG-T Mild Hybrid',
    engine_capacity: '1332 cc',
    horsepower: 140,
    condition: 'Excellent',
    city: 'Nottingham',
    location: 'City Centre, Nottingham, UK',
    description: 'UK’s favorite crossover 2023 Nissan Qashqai N-Connecta. NissanConnect 12.3" Touchscreen, Around View 360 Camera, Wireless Apple CarPlay, and 18" Diamond Cut Alloys.',
    images: [
      'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1200&q=80',
    features: ['12.3" NissanConnect Display', 'Around View 360 Camera', 'Wireless Apple CarPlay', 'Lane Keep Assist', 'Dual Zone Climate'],
    badge: 'Popular Family Choice',
    rating: 4.7,
    status: 'approved',
    is_featured: false,
    views_count: 90,
    seller_name: 'Trent Valley Nissan Centre',
    seller_phone: '+44 115 496 0331',
    seller_email: 'sales@trentvalleynissan.co.uk',
    is_inspected: true,
    inspection_rating: 9.5,
    inspection_notes: 'Passed complete safety inspection. Brakes 90%, tires 85%, full digital service log.',
    inspected_at: new Date('2026-07-21T08:30:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 16. Toyota GR Yaris
  {
    title: '2022 Toyota Yaris GR 1.6 Turbo 4WD Circuit Pack 3dr',
    brand: 'Toyota',
    model: 'GR Yaris',
    year: 2022,
    price: 33950,
    currency: 'GBP',
    mileage: 9400,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    body_type: 'Hatchback',
    exterior_color: 'Pure White',
    interior_color: 'Ultrasuede GR Sports Seats',
    color: 'Pure White',
    engine: '1.6L 3-Cylinder Turbo',
    engine_capacity: '1618 cc',
    horsepower: 261,
    condition: 'Collector Grade',
    city: 'Bath',
    location: 'Royal Crescent, Bath, UK',
    description: 'Sought-after Toyota GR Yaris with Circuit Pack (Front & Rear Torsen Limited-Slip Differentials, GR Circuit Suspension, 18" BBS Forged Alloys, Red GR Brake Calipers).',
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
    features: ['Circuit Pack', 'Front & Rear Torsen LSDs', 'BBS Forged Alloys', 'GR Four AWD System', 'Michelin Pilot Sport 4S Tires'],
    badge: 'Rally Special Verified',
    rating: 5.0,
    status: 'approved',
    is_featured: true,
    views_count: 340,
    seller_name: 'Cotswold Motorsport Cars',
    seller_phone: '+44 1225 496 0881',
    seller_email: 'sales@cotswoldmotorsport.co.uk',
    is_inspected: true,
    inspection_rating: 9.9,
    inspection_notes: 'GR Four drivetrain & Torsen LSDs thoroughly tested. Zero track damage, spotless undersides.',
    inspected_at: new Date('2026-07-22T10:15:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 17. Hyundai Ioniq 5
  {
    title: '2023 Hyundai Ioniq 5 77kWh Ultimate AWD 5dr Auto',
    brand: 'Hyundai',
    model: 'Ioniq 5',
    year: 2023,
    price: 36800,
    currency: 'GBP',
    mileage: 12100,
    transmission: 'Automatic',
    fuel_type: 'Electric',
    body_type: 'SUV',
    exterior_color: 'Gravity Gold Matte',
    interior_color: 'Light Grey Leather',
    color: 'Gravity Gold',
    engine: 'Dual Electric Motor 325 PS',
    engine_capacity: '77.4 kWh',
    horsepower: 325,
    condition: 'Certified EV',
    city: 'Cardiff',
    location: 'Cardiff Bay, Wales, UK',
    description: 'Award-winning Hyundai Ioniq 5 Ultimate AWD with Vision Roof, Relaxation Seats, Bose Premium Audio, Vehicle-to-Load (V2L), 800V Ultra-Fast Charging, and 20" Alloys.',
    images: [
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1536700503339-1e4b06520771?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80',
    features: ['800V Ultra-Fast Charging', 'V2L Vehicle-to-Load Tech', 'Bose Premium Audio', 'Relaxation Seats', 'Vision Glass Roof'],
    badge: 'EV Technology Leader',
    rating: 4.9,
    status: 'approved',
    is_featured: false,
    views_count: 160,
    seller_name: 'Welsh EV Centre',
    seller_phone: '+44 29 2049 0992',
    seller_email: 'info@welshev.co.uk',
    is_inspected: true,
    inspection_rating: 9.7,
    inspection_notes: 'Battery health verified at 99.1%. Charging ports and 800V inverter functioning at maximum efficiency.',
    inspected_at: new Date('2026-07-21T14:10:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 18. Polestar 2
  {
    title: '2023 Polestar 2 Long Range Dual Motor Pilot Plus 5dr Auto',
    brand: 'Polestar',
    model: 'Polestar 2',
    year: 2023,
    price: 35400,
    currency: 'GBP',
    mileage: 13800,
    transmission: 'Automatic',
    fuel_type: 'Electric',
    body_type: 'Sedan',
    exterior_color: 'Thunder Grey',
    interior_color: 'WeaveTech Slate Seats',
    color: 'Thunder Grey',
    engine: 'Dual Electric Motor 408 hp',
    engine_capacity: '78 kWh',
    horsepower: 408,
    condition: 'Certified EV',
    city: 'Belfast',
    location: 'Titanic Quarter, Belfast, UK',
    description: 'Sleek Scandinavian Polestar 2 Long Range Dual Motor with Pilot Pack (Pixel LED Headlights, Driver Assist), Plus Pack (Harman Kardon, Panoramic Roof, Heat Pump).',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',
    features: ['Pilot & Plus Packs', 'Pixel LED Headlights', 'Harman Kardon Audio', 'Fixed Panoramic Roof', 'Google Android Automotive OS'],
    badge: 'EV Certified',
    rating: 4.8,
    status: 'approved',
    is_featured: false,
    views_count: 125,
    seller_name: 'Belfast EV Specialists',
    seller_phone: '+44 28 9049 0113',
    seller_email: 'sales@belfastev.co.uk',
    is_inspected: true,
    inspection_rating: 9.6,
    inspection_notes: 'Passed 200-point inspection. Battery capacity 98.7%, software upgraded to latest Polestar release.',
    inspected_at: new Date('2026-07-20T11:45:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 19. Alfa Romeo Giulia
  {
    title: '2022 Alfa Romeo Giulia 2.0 Turbo Veloce 4dr Auto',
    brand: 'Alfa Romeo',
    model: 'Giulia',
    year: 2022,
    price: 28990,
    currency: 'GBP',
    mileage: 17200,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    body_type: 'Sedan',
    exterior_color: 'Misano Blue Metallic',
    interior_color: 'Black Sports Leather Seats with Red Stitching',
    color: 'Misano Blue',
    engine: '2.0L Turbocharged 280 hp',
    engine_capacity: '1995 cc',
    horsepower: 280,
    condition: 'Excellent',
    city: 'Aberdeen',
    location: 'West End, Aberdeen, UK',
    description: 'Passion-infused Alfa Romeo Giulia Veloce in Misano Blue. Equipped with Alfa Q2 Limited Slip Differential, Carbon Fiber Driveshaft, Harman Kardon Audio, and 19" 5-hole Dark alloys.',
    images: [
      'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80',
    features: ['Alfa Q2 Limited Slip Diff', 'Harman Kardon Audio', '19" Dark 5-Hole Alloys', 'Aluminum Shift Paddles', 'DNA Drive Selector'],
    badge: 'Italian Sport Saloon',
    rating: 4.8,
    status: 'approved',
    is_featured: false,
    views_count: 108,
    seller_name: 'Grampian Performance Automobiles',
    seller_phone: '+44 1224 496 0331',
    seller_email: 'sales@grampianauto.co.uk',
    is_inspected: true,
    inspection_rating: 9.5,
    inspection_notes: 'Inspected by Peter Parker. Carbon driveshaft and 280hp turbo engine in perfect health.',
    inspected_at: new Date('2026-07-19T15:10:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 20. Vauxhall Corsa-e
  {
    title: '2023 Vauxhall Corsa-e 50kWh Ultimate 5dr Auto',
    brand: 'Vauxhall',
    model: 'Corsa-e',
    year: 2023,
    price: 18990,
    currency: 'GBP',
    mileage: 10500,
    transmission: 'Automatic',
    fuel_type: 'Electric',
    body_type: 'Hatchback',
    exterior_color: 'Voltaic Blue with Black Roof',
    interior_color: 'Alcantara Seat Trim',
    color: 'Voltaic Blue',
    engine: 'Electric Motor 136 PS',
    engine_capacity: '50 kWh',
    horsepower: 136,
    condition: 'Certified EV',
    city: 'Norwich',
    location: 'City Centre, Norwich, UK',
    description: 'Top specification 2023 Vauxhall Corsa-e Ultimate with IntelliLux LED Matrix Headlights, 10" Multimedia Navi Pro, Massage Driver Seat, Heated Seats & Wheel, and 17" Bi-Color Alloys.',
    images: [
      'https://images.unsplash.com/photo-1617654112365-307921291f42?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1617654112365-307921291f42?auto=format&fit=crop&w=1200&q=80',
    features: ['IntelliLux LED Matrix Headlights', '10" Multimedia Navi Pro', 'Massage Driver Seat', 'Heated Seats & Wheel', '100kW Fast Charge Capable'],
    badge: 'Affordable EV',
    rating: 4.6,
    status: 'approved',
    is_featured: false,
    views_count: 75,
    seller_name: 'East Anglia Motor Company',
    seller_phone: '+44 1603 496 0221',
    seller_email: 'sales@eamc.co.uk',
    is_inspected: true,
    inspection_rating: 9.4,
    inspection_notes: 'Battery health test passed at 99.0%. Ideal city EV with zero emissions.',
    inspected_at: new Date('2026-07-21T09:20:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 21. Honda Civic Type R
  {
    title: '2023 Honda Civic Type R 2.0 VTEC Turbo FL5 5dr',
    brand: 'Honda',
    model: 'Civic Type R',
    year: 2023,
    price: 46500,
    currency: 'GBP',
    mileage: 6800,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    body_type: 'Hatchback',
    exterior_color: 'Championship White',
    interior_color: 'Red Suede Type R Bucket Seats',
    color: 'Championship White',
    engine: '2.0L VTEC Turbo 329 PS',
    engine_capacity: '1996 cc',
    horsepower: 329,
    condition: 'Like New',
    city: 'Leicester',
    location: 'Oadby, Leicester, UK',
    description: 'Ultimate FWD performance car FL5 Honda Civic Type R in iconic Championship White. Triple Exhaust Outlets, LogR Data Logger, Brembo 4-piston brakes, and 19" Lightweight Matte Black Alloys.',
    images: [
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80',
    features: ['Type R LogR Data Logger', 'Brembo Brakes', 'Helical Limited Slip Diff', 'Championship White Finish', 'Type R Bucket Seats'],
    badge: 'Track Legend',
    rating: 5.0,
    status: 'approved',
    is_featured: true,
    views_count: 390,
    seller_name: 'Midlands Performance Honda',
    seller_phone: '+44 116 496 0773',
    seller_email: 'sales@midlandshonda.co.uk',
    is_inspected: true,
    inspection_rating: 9.9,
    inspection_notes: 'Passed 200-point inspection. VTEC Turbo engine and rev-match manual gearbox pristine.',
    inspected_at: new Date('2026-07-22T13:00:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 22. Cupra Formentor
  {
    title: '2023 Cupra Formentor 2.0 TSI VZ3 310 PS 4Drive DSG 5dr',
    brand: 'Cupra',
    model: 'Formentor',
    year: 2023,
    price: 32990,
    currency: 'GBP',
    mileage: 14800,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    body_type: 'SUV',
    exterior_color: 'Petrol Blue Matte',
    interior_color: 'Petrol Blue Nappa Leather Bucket Seats',
    color: 'Petrol Blue',
    engine: '2.0L TSI Turbo 310 PS',
    engine_capacity: '1984 cc',
    horsepower: 310,
    condition: 'Excellent',
    city: 'Exeter',
    location: 'Quayside, Exeter, UK',
    description: 'Striking Cupra Formentor VZ3 310 PS in Matte Petrol Blue. Features Brembo Brakes, BeatsAudio System, Panoramic Glass Roof, DCC Dynamic Chassis Control, and 19" Copper Alloy Wheels.',
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1519245659620-e859806a8d3b?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80',
    features: ['Brembo Performance Brakes', 'BeatsAudio System', 'Matte Paint Finish', 'Dynamic Chassis Control', '12" Navigation Screen'],
    badge: 'Performance SUV',
    rating: 4.8,
    status: 'approved',
    is_featured: false,
    views_count: 135,
    seller_name: 'Devon & Cornwall Performance Cars',
    seller_phone: '+44 1392 496 0331',
    seller_email: 'sales@dcperformance.co.uk',
    is_inspected: true,
    inspection_rating: 9.6,
    inspection_notes: 'Brembo braking depth >90%, 4Drive system tested in all drive modes.',
    inspected_at: new Date('2026-07-20T16:30:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 23. Kia EV6
  {
    title: '2023 Kia EV6 77.4kWh GT-Line S AWD 5dr Auto',
    brand: 'Kia',
    model: 'EV6',
    year: 2023,
    price: 39950,
    currency: 'GBP',
    mileage: 11900,
    transmission: 'Automatic',
    fuel_type: 'Electric',
    body_type: 'SUV',
    exterior_color: 'Yacht Blue Metallic',
    interior_color: 'Black Suede Seats with White Vegan Leather Bolsters',
    color: 'Yacht Blue',
    engine: 'Dual Electric Motor 321 bhp',
    engine_capacity: '77.4 kWh',
    horsepower: 321,
    condition: 'Certified EV',
    city: 'York',
    location: 'City Centre, York, UK',
    description: 'European Car of the Year Kia EV6 GT-Line S AWD. 800V Ultra-Fast Charging, Meridian Premium Sound, Augmented Reality Head-Up Display, Sunroof, and Remote Smart Park Assist.',
    images: [
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1536700503339-1e4b06520771?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80',
    features: ['800V Charging System', 'AR Head-Up Display', 'Meridian Premium Audio', 'Remote Smart Parking', 'Sunroof'],
    badge: 'Award Winner',
    rating: 4.9,
    status: 'approved',
    is_featured: false,
    views_count: 148,
    seller_name: 'Yorkshire EV Centre',
    seller_phone: '+44 1904 496 0882',
    seller_email: 'info@yorkshireev.co.uk',
    is_inspected: true,
    inspection_rating: 9.7,
    inspection_notes: 'HV Battery SOH at 99.3%. All ADAS sensors calibrated and operating perfectly.',
    inspected_at: new Date('2026-07-21T12:00:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 24. Lotus Emira
  {
    title: '2023 Lotus Emira 3.5 V6 First Edition 2dr Manual',
    brand: 'Lotus',
    model: 'Emira',
    year: 2023,
    price: 72500,
    currency: 'GBP',
    mileage: 5200,
    transmission: 'Manual',
    fuel_type: 'Petrol',
    body_type: 'Coupe',
    exterior_color: 'Seneca Blue',
    interior_color: 'Black Alcantara with Yellow Stitching',
    color: 'Seneca Blue',
    engine: '3.5L Supercharged V6',
    engine_capacity: '3456 cc',
    horsepower: 400,
    condition: 'Pristine',
    city: 'Chester',
    location: 'Chester Rows, Chester, UK',
    description: 'Pure British sports car 2023 Lotus Emira V6 First Edition in Seneca Blue with Drivers Pack (Sports Suspension, Goodyear Eagle F1 SuperSport Tires), KEF 10-channel Audio, and Open-Mesh Gearlinkage.',
    images: [
      'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1611821064430-0d4187063f25?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80',
    features: ['KEF 10-Channel Uni-Q Audio', 'Lotus Drivers Pack', 'Open Gear Mechanism', 'Exposed Mechanical Linkage', 'Full Alcantara Pack'],
    badge: 'British Sports Car',
    rating: 5.0,
    status: 'approved',
    is_featured: true,
    views_count: 450,
    seller_name: 'Cheshire Lotus Specialists',
    seller_phone: '+44 1244 496 0112',
    seller_email: 'sales@cheshirelotus.co.uk',
    is_inspected: true,
    inspection_rating: 9.9,
    inspection_notes: 'Supercharged V6 & Toyota-based manual transmission passed thorough Lotus certified evaluation.',
    inspected_at: new Date('2026-07-22T15:30:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  },

  // 25. Lexus RX 450h
  {
    title: '2022 Lexus RX 450h 3.5 V6 F Sport Takumi Pack 5dr Auto',
    brand: 'Lexus',
    model: 'RX 450h',
    year: 2022,
    price: 42990,
    currency: 'GBP',
    mileage: 19800,
    transmission: 'Automatic',
    fuel_type: 'Hybrid',
    body_type: 'SUV',
    exterior_color: 'F Sport White Nova Metallic',
    interior_color: 'Dark Rose Leather with Smooth Leather Inlays',
    color: 'White Nova',
    engine: '3.5L V6 Self-Charging Hybrid',
    engine_capacity: '3456 cc',
    horsepower: 313,
    condition: 'Certified Used',
    city: 'Brighton',
    location: 'Seafront, Brighton, UK',
    description: 'Refined 2022 Lexus RX 450h F Sport with Takumi Pack (Mark Levinson 15-Speaker Audio, BladeScan Adaptive High-Beam System, Panoramic Sunroof, Head-Up Display, Adaptive Variable Suspension).',
    images: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=80'
    ],
    image_url: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    features: ['Mark Levinson 15-Speaker Audio', 'Takumi Pack', 'BladeScan AHS Headlights', 'Adaptive Variable Suspension', 'Panoramic Roof'],
    badge: 'Reliability Champion',
    rating: 4.9,
    status: 'approved',
    is_featured: false,
    views_count: 120,
    seller_name: 'Sussex Lexus Specialists',
    seller_phone: '+44 1273 496 0551',
    seller_email: 'sales@sussexlexus.co.uk',
    is_inspected: true,
    inspection_rating: 9.8,
    inspection_notes: 'Lexus Hybrid Health Check passed with 100% score. Legendary V6 hybrid smoothness confirmed.',
    inspected_at: new Date('2026-07-21T17:00:00Z').toISOString(),
    inspector_id: INSPECTOR.id,
    inspector_name: INSPECTOR.name,
    inspector_email: INSPECTOR.email,
    inspector_phone: INSPECTOR.phone,
  }
];

async function seed() {
  console.log("🧹 STEP 1: Deleting all existing car records...");
  const { error: deleteErr } = await supabase
    .from('cars')
    .delete()
    .neq('id', '00000000-0000-0000-0000-000000000000');

  if (deleteErr) {
    console.error("❌ Failed to clear existing cars:", deleteErr);
    process.exit(1);
  }
  console.log("✅ Cleared previous cars table!");

  console.log(`🚗 STEP 2: Seeding ${UK_25_CARS.length} distinct UK car listings...`);
  
  const { data: inserted, error: insertErr } = await supabase
    .from('cars')
    .insert(UK_25_CARS)
    .select('id, title, brand, model, price, currency, city, is_inspected, inspector_name');

  if (insertErr) {
    console.error("❌ Failed to insert UK car listings:", insertErr);
    process.exit(1);
  }

  console.log(`🎉 Successfully seeded ALL ${inserted.length} verified UK car listings!`);
  console.table(inserted.map((c, i) => ({
    '#': i + 1,
    ID: c.id.substring(0, 8),
    Title: c.title,
    Brand: c.brand,
    Price: `£${c.price.toLocaleString()}`,
    City: c.city,
    Inspector: c.inspector_name
  })));
}

seed();
